error: Don't print error if context is cancelled
- Get rid of dependency on logrus - anyway we will be moving to zerolog
- Don't print any error if the context was cancelled - interrupted by
  signal

Signed-off-by: Mike Sul <mike.sul@foundries.io>